<%
require 'bcdatabase'

bcdb = Bcdatabase.load
%>

development:
  adapter: <%= 'jdbc' if RUBY_PLATFORM =~ /java/ %>postgresql
  database: ncs_navigator_pancakes
  username: ncs_navigator_pancakes
  password: ncs_navigator_pancakes
  host: localhost
  pool: 20

<%= bcdb.test :public_ci_postgresql9, :ncs_navigator_pancakes %>
<%= bcdb.staging :ncsdb_staging, :ncs_navigator_pancakes %>
<%= bcdb.production :ncsdb_prod, :ncs_navigator_pancakes %>
<%= bcdb.redis_development :local_redis, :ncs_navigator_pancakes %>
<%= bcdb.redis_staging :ncsredis_staging, :ncs_navigator_pancakes %>
<%= bcdb.redis_production :ncsredis_prod, :ncs_navigator_pancakes %>
