<%
require 'bcdatabase'

bcdb = Bcdatabase.load
%>

development:
  adapter: <%= 'jdbc' if RUBY_PLATFORM =~ /java/ %>postgresql
  database: ncs_navigator_pancakes
  username: ncs_navigator_pancakes
  password: ncs_navigator_pancakes
  host: localhost
  pool: 20

test:
  adapter: <%= 'jdbc' if RUBY_PLATFORM =~ /java/ %>postgresql
  database: ncs_navigator_pancakes_test
  username: ncs_navigator_pancakes_test
  password: ncs_navigator_pancakes_test
  host: localhost
  pool: 20

<%= bcdb.ci :public_ci_postgresql9, :ncs_navigator_pancakes %>
<%= bcdb.production :ncsdb_prod, :ncs_navigator_pancakes %>
<%= bcdb.redis_development :local_redis, :ncs_navigator_pancakes %>
<%= bcdb.redis_production :ncsredis_prod, :ncs_navigator_pancakes %>
